"""create_initial_tables

Revision ID: c642e2b83362
Revises: 60c783b9d11a
Create Date: 2023-09-07 22:04:50.149298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c642e2b83362'
down_revision: Union[str, None] = '60c783b9d11a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_figure', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'transaction_figure')
    # ### end Alembic commands ###
